"""Añadir campos opcionales

Revision ID: 53d8bf643ad5
Revises: c77bdec0cb76
Create Date: 2025-12-13 15:08:49.894116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d8bf643ad5'
down_revision = 'c77bdec0cb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domicilio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_column('provincia')
        batch_op.drop_column('cp')
        batch_op.drop_column('localidad')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('email')
        batch_op.drop_column('provincia')
        batch_op.drop_column('cp')
        batch_op.drop_column('localidad')
        batch_op.drop_column('domicilio')

    # ### end Alembic commands ###
