"""Añadir geo y tablas registro incidencia

Revision ID: b3c76a2d9ec4
Revises: 53d8bf643ad5
Create Date: 2026-01-19 09:50:09.442964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c76a2d9ec4'
down_revision = '53d8bf643ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencia',
    sa.Column('id_incidencia', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajador.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_incidencia')
    )
    op.create_table('registro',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajador.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('radio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('radio')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    op.drop_table('registro')
    op.drop_table('incidencia')
    # ### end Alembic commands ###
